-- AUTH DATABASE

CREATE DATABASE IF NOT EXISTS auth_db;
USE auth_db;

-- ROLES TABLE
CREATE TABLE IF NOT EXISTS roles (
    role_id INT PRIMARY KEY,
    role_name VARCHAR(20) NOT NULL
);

-- USERS TABLE
CREATE TABLE IF NOT EXISTS users (
    user_id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(60) NOT NULL,
    role_id INT NOT NULL,
    FOREIGN KEY (role_id) REFERENCES roles(role_id)
);
-- DEFAULT ROLES
INSERT INTO roles VALUES
(1,'PRODUCER'),
(2,'ADMIN'),
(3,'CUSTOMER');